---
title: "example code"
author: "Richard Cottrell"
date: '2022-05-17'
output: html_document
---

```{r}
library(tidyverse)
library(here)

here()
```

```{r}
lca_data <- read_csv(here("Outputs/lca_model_data_no-summary.csv")) %>% filter(taxa == "shrimp") %>% select(study_id, iso3c, clean_sci_name, taxa, intensity, system, total_ghg ) %>% arrange(iso3c)



(lca_by_country <- lca_data %>% 
  group_by(iso3c) %>% 
  summarise(mean_ghg = mean(total_ghg),
            sd_ghg = sd(total_ghg)))

(total_ghg <- lca_data %>% 
  summarise(mean_ghg = mean(total_ghg),
            sd_ghg = sd(total_ghg)) %>% 
  add_column(iso3c = "Other") %>% 
  select(iso3c, mean_ghg, sd_ghg))


```
For transportation

```{r}


output <- list()

for(i in 1:1000){
  
  emissions_factor <- rnorm(n=1, mean = 12.41, sd=1.83)
  
  trade_volume <- 4
  
  km_travelled <- 3
 
  calc <- emissions_factor*trade_volume*km_travelled
  
  output <- c(output, calc)
  
  
}

simple_ouput <- unlist(output)

mean(simple_ouput)
sd(simple_ouput)

```

